# Site settings
title: Kirby Powell
description: >
  This is the personal blog of Kirby Powell. It's built in jekyll using
  the Daktilo theme. We'll see what this place ends up as!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kirbpowell.github.io" # the base hostname & protocol for your site

author:
  fullname: Kirby Powell
  github: kirbpowell
  linkedin: https://www.linkedin.com/in/kirbypowell
  # disqus: your_disqus_username

google_analytics: 'UA-69804968-1'

# Build settings
markdown: redcarpet
